src/Entity/Checklistes.php
<?php

namespace App\Entity;

use ApiPlatform\Core\Annotation\ApiResource;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ApiResource()
 * @ORM\Entity(repositoryClass="App\Repository\ChecklistesRepository")
 */
class Checklistes
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nom;

    /**
     * @ORM\Column(type="datetime")
     */
    private $date_limite_vaccin;

    /**
     * @ORM\Column(type="datetime")
     */
    private $date_depart;

    /**
    * @ORM\ManyToMany(targetEntity="App\Entity\Documents", inversedBy="Checklistes")
    */
    private $documents;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getDateLimiteVaccin(): ?\DateTimeInterface
    {
        return $this->date_limite_vaccin;
    }

    public function setDateLimiteVaccin(\DateTimeInterface $date_limite_vaccin): self
    {
        $this->date_limite_vaccin = $date_limite_vaccin;

        return $this;
    }

    public function getDateDepart(): ?\DateTimeInterface
    {
        return $this->date_depart;
    }

    public function setDateDepart(\DateTimeInterface $date_depart): self
    {
        $this->date_depart = $date_depart;

        return $this;
    }
}

src/Form/ChecklistesType.php
<?php

namespace App\Form;

use App\Entity\Checklistes;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ChecklistesType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('nom')
            ->add('date_limite_vaccin')
            ->add('date_depart')
            ->add('documents')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Checklistes::class,
        ]);
    }
}

templates/checklistes/_delete_form.html.twig
<form method="post" action="{{ path('checklistes_delete', {'id': checkliste.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ checkliste.id) }}">
    <button class="btn">Delete</button>
</form>

templates/checklistes/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/checklistes/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Checklistes{% endblock %}

{% block body %}
    <h1>Edit Checklistes</h1>

    {{ include('checklistes/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('checklistes_index') }}">back to list</a>

    {{ include('checklistes/_delete_form.html.twig') }}
{% endblock %}

templates/checklistes/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Checklistes index{% endblock %}

{% block body %}
    <h1>Checklistes index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Nom</th>
                <th>Date_limite_vaccin</th>
                <th>Date_depart</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for checkliste in checklistes %}
            <tr>
                <td>{{ checkliste.id }}</td>
                <td>{{ checkliste.nom }}</td>
                <td>{{ checkliste.dateLimiteVaccin ? checkliste.dateLimiteVaccin|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ checkliste.dateDepart ? checkliste.dateDepart|date('Y-m-d H:i:s') : '' }}</td>
                <td>
                    <a href="{{ path('checklistes_show', {'id': checkliste.id}) }}">show</a>
                    <a href="{{ path('checklistes_edit', {'id': checkliste.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="5">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('checklistes_new') }}">Create new</a>
{% endblock %}

templates/checklistes/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Checklistes{% endblock %}

{% block body %}
    <h1>Create new Checklistes</h1>

    {{ include('checklistes/_form.html.twig') }}

    <a href="{{ path('checklistes_index') }}">back to list</a>
{% endblock %}

templates/checklistes/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Checklistes{% endblock %}

{% block body %}
    <h1>Checklistes</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ checkliste.id }}</td>
            </tr>
            <tr>
                <th>Nom</th>
                <td>{{ checkliste.nom }}</td>
            </tr>
            <tr>
                <th>Date_limite_vaccin</th>
                <td>{{ checkliste.dateLimiteVaccin ? checkliste.dateLimiteVaccin|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Date_depart</th>
                <td>{{ checkliste.dateDepart ? checkliste.dateDepart|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('checklistes_index') }}">back to list</a>

    <a href="{{ path('checklistes_edit', {'id': checkliste.id}) }}">edit</a>

    {{ include('checklistes/_delete_form.html.twig') }}
{% endblock %}