src/Entity/Voyage.php
<?php

namespace App\Entity;

use ApiPlatform\Core\Annotation\ApiResource;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ApiResource()
 * @ORM\Entity(repositoryClass="App\Repository\VoyageRepository")
 */
class Voyage
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $destination;

    /**
     * @ORM\Column(type="datetime")
     */
    private $historique;

    /**
     * @ORM\Column(type="datetime")
     */
    private $date_depart;

    /**
     * @ORM\Column(type="datetime")
     */
    private $date_arriver;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $mode_paiements;


    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Pays", mappedBy="Voyage")
     */
    private $pays;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDestination(): ?string
    {
        return $this->destination;
    }

    public function setDestination(string $destination): self
    {
        $this->destination = $destination;

        return $this;
    }

    public function getHistorique(): ?\DateTimeInterface
    {
        return $this->historique;
    }

    public function setHistorique(\DateTimeInterface $historique): self
    {
        $this->historique = $historique;

        return $this;
    }

    public function getDateDepart(): ?\DateTimeInterface
    {
        return $this->date_depart;
    }

    public function setDateDepart(\DateTimeInterface $date_depart): self
    {
        $this->date_depart = $date_depart;

        return $this;
    }

    public function getDateArriver(): ?\DateTimeInterface
    {
        return $this->date_arriver;
    }

    public function setDateArriver(\DateTimeInterface $date_arriver): self
    {
        $this->date_arriver = $date_arriver;

        return $this;
    }

    public function getModePaiements(): ?string
    {
        return $this->mode_paiements;
    }

    public function setModePaiements(string $mode_paiements): self
    {
        $this->mode_paiements = $mode_paiements;

        return $this;
    }
}

src/Form/VoyageType.php
<?php

namespace App\Form;

use App\Entity\Voyage;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class VoyageType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('destination')
            ->add('historique')
            ->add('date_depart')
            ->add('date_arriver')
            ->add('mode_paiements')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Voyage::class,
        ]);
    }
}

templates/voyage/_delete_form.html.twig
<form method="post" action="{{ path('voyage_delete', {'id': voyage.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ voyage.id) }}">
    <button class="btn">Delete</button>
</form>

templates/voyage/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/voyage/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Voyage{% endblock %}

{% block body %}
    <h1>Edit Voyage</h1>

    {{ include('voyage/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('voyage_index') }}">back to list</a>

    {{ include('voyage/_delete_form.html.twig') }}
{% endblock %}

templates/voyage/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Voyage index{% endblock %}

{% block body %}
    <h1>Voyage index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Destination</th>
                <th>Historique</th>
                <th>Date_depart</th>
                <th>Date_arriver</th>
                <th>Mode_paiements</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for voyage in voyages %}
            <tr>
                <td>{{ voyage.id }}</td>
                <td>{{ voyage.destination }}</td>
                <td>{{ voyage.historique ? voyage.historique|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ voyage.dateDepart ? voyage.dateDepart|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ voyage.dateArriver ? voyage.dateArriver|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ voyage.modePaiements }}</td>
                <td>
                    <a href="{{ path('voyage_show', {'id': voyage.id}) }}">show</a>
                    <a href="{{ path('voyage_edit', {'id': voyage.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="7">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('voyage_new') }}">Create new</a>
{% endblock %}

templates/voyage/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Voyage{% endblock %}

{% block body %}
    <h1>Create new Voyage</h1>

    {{ include('voyage/_form.html.twig') }}

    <a href="{{ path('voyage_index') }}">back to list</a>
{% endblock %}

templates/voyage/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Voyage{% endblock %}

{% block body %}
    <h1>Voyage</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ voyage.id }}</td>
            </tr>
            <tr>
                <th>Destination</th>
                <td>{{ voyage.destination }}</td>
            </tr>
            <tr>
                <th>Historique</th>
                <td>{{ voyage.historique ? voyage.historique|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Date_depart</th>
                <td>{{ voyage.dateDepart ? voyage.dateDepart|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Date_arriver</th>
                <td>{{ voyage.dateArriver ? voyage.dateArriver|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Mode_paiements</th>
                <td>{{ voyage.modePaiements }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('voyage_index') }}">back to list</a>

    <a href="{{ path('voyage_edit', {'id': voyage.id}) }}">edit</a>

    {{ include('voyage/_delete_form.html.twig') }}
{% endblock %}